# Generated by Django 4.2.7 on 2023-12-12 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_rename_img_users_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
