# Generated by Django 4.2.7 on 2023-12-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_images_name_remove_users_imgs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
