# Generated by Django 4.2.7 on 2023-12-12 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_remove_images_user_name_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friend_id',
            field=models.ManyToManyField(blank=True, default=[], related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
